#!/usr/bin/env bash
# No_Gas_Labs™ Rollback Script
# Auto-generated by Ralph Loop
# Last updated: Iteration 1

set -euo pipefail

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "No_Gas_Labs™ Ralph Loop Rollback Utility"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check we're on mirror branch
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
if [[ "$BRANCH" != "mirror" ]]; then
  echo "❌ Not on mirror branch (currently: $BRANCH)"
  exit 1
fi

echo "Available rollback points (last 20):"
echo ""
git tag -l "rollback-iter-*" | sort -Vr | head -20 | while read -r tag; do
  ITER=$(echo "$tag" | sed 's/rollback-iter-//')
  VALIDATED=$(git tag -l "validated-iter-$ITER" | wc -l)
  if [ "$VALIDATED" -eq 1 ]; then
    echo "  ✅ Iteration $ITER (validated)"
  else
    echo "  ⚠️  Iteration $ITER (not validated)"
  fi
done

echo ""
echo "Current iteration: $(cat staging/ralph_state.json | grep -o '"iteration":[0-9]*' | cut -d: -f2)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Enter iteration number to rollback to (or 'cancel'):"
read -r ITER

if [ "$ITER" = "cancel" ] || [ -z "$ITER" ]; then
  echo "❌ Rollback cancelled"
  exit 0
fi

# Validate iteration number
if ! [[ "$ITER" =~ ^[0-9]+$ ]]; then
  echo "❌ Invalid iteration number: $ITER"
  exit 1
fi

TAG="rollback-iter-$ITER"

# Check tag exists
if ! git tag -l | grep -q "^$TAG$"; then
  echo "❌ Rollback point not found: $TAG"
  echo "Available tags:"
  git tag -l "rollback-iter-*" | sort -Vr | head -10
  exit 1
fi

# Show what will be lost
CURRENT_ITER=$(cat staging/ralph_state.json | grep -o '"iteration":[0-9]*' | cut -d: -f2)
LOST_ITERS=$((CURRENT_ITER - ITER))

echo ""
echo "⚠️  WARNING: This will rollback $LOST_ITERS iteration(s)"
echo "⚠️  Current: iteration $CURRENT_ITER"
echo "⚠️  Target:  iteration $ITER"
echo "⚠️  All work from iterations $((ITER+1)) to $CURRENT_ITER will be LOST"
echo ""
echo "Type 'ROLLBACK' to confirm (case-sensitive):"
read -r CONFIRM

if [ "$CONFIRM" != "ROLLBACK" ]; then
  echo "❌ Rollback cancelled (confirmation failed)"
  exit 0
fi

echo ""
echo "🔄 Rolling back to iteration $ITER..."

# Create emergency backup tag
EMERGENCY_TAG="emergency-backup-$(date +%Y%m%d-%H%M%S)"
git tag "$EMERGENCY_TAG"
echo "✅ Emergency backup created: $EMERGENCY_TAG"

# Perform rollback
git reset --hard "$TAG"

# Force push with lease (safer than --force)
git push origin mirror --force-with-lease || {
  echo "❌ Push failed - restoring from emergency backup"
  git reset --hard "$EMERGENCY_TAG"
  exit 1
}

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ ROLLBACK COMPLETE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Rolled back to: iteration $ITER"
echo "Emergency backup: $EMERGENCY_TAG (can be deleted later)"
echo ""
echo "To continue Ralph loop from this point:"
echo "  1. Verify state: cat staging/ralph_state.json"
echo "  2. Resume: (Manus will auto-detect and continue)"
echo ""
